version: '3'

services:
  cloud-provider:
    image: bitnami/minio:latest
    networks:
      - flysystem
    ports:
      - "9898:9000"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ACCESS_KEY=flysystem
      - MINIO_SECRET_KEY=helloworld
      - MINIO_DEFAULT_BUCKETS=test-bucket:public
  php-tests:
    image: moderntribe/squareone-php:73-latest
    user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
    networks:
      - flysystem
    depends_on:
      - "cloud-provider"
    volumes:
      - test_data:/application/www

volumes:
  test_data:
    driver_opts:
      type: none
      device: ./ # relative to this project's root
      o: bind
  minio_data:

networks:
  flysystem:
    driver: bridge
