version: '3'

services:
  php-tests:
    image: moderntribe/squareone-php:73-latest
    user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
    networks:
      - flysystem
    depends_on:
      - "s3server"
    volumes:
      - test_data:/application/www
  s3server:
    image: bitnami/minio:latest
    user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
    hostname: s3server
    networks:
      flysystem:
        aliases:
          - s3server
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=flysystem
      - MINIO_SECRET_KEY=helloworld
      - MINIO_DEFAULT_BUCKETS=test-bucket:public

volumes:
  test_data:
    driver_opts:
      type: none
      device: ./ # relative to this project's root
      o: bind

networks:
  flysystem:
    driver: "bridge"
