version: '3'

services:
  php-tests:
    image: moderntribe/squareone-php:73-latest
    volumes:
      - test_data:/application/www
  minio:
    image: bitnami/minio:latest
    networks:
      default:
        aliases:
          - tests3
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=flysystem
      - MINIO_SECRET_KEY=helloworld
      - MINIO_DEFAULT_BUCKETS=test-bucket:public

volumes:
  test_data:
    driver_opts:
      type: none
      device: ./ # relative to this project's root
      o: bind

networks:
  default:
