version: '3'

services:
  cloud-provider:
    container_name: cloud-provider
    image: bitnami/minio:2022.4.1
    networks:
      - flysystem
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=flysystem
      - MINIO_ROOT_PASSWORD=helloworld
      - MINIO_SERVER_ACCESS_KEY=flysystem
      - MINIO_SERVER_SECRET_KEY=helloworld
      - MINIO_DEFAULT_BUCKETS=test-bucket:public
  php-tests:
    container_name: flysystem-wrapper-tests
    image: moderntribe/squareone-php:73-latest
    user: "${SQ1_UID:-1000}:${SQ1_GID:-1000}"
    networks:
      - flysystem
    depends_on:
      - "cloud-provider"
    volumes:
      - test_data:/application/www

volumes:
  test_data:
    driver_opts:
      type: none
      device: ./ # relative to this project's root
      o: bind
  minio_data:

networks:
  flysystem:
    driver: bridge
